# https://fabricmc.net/develop
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.3
minecraft_compat_version=26.3.x

loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=2.5.0+26.3
maven_group=dev.doublekekse
archives_base_name=map_utils

# Dependencies
fabric_api_version=0.160.7+26.3
trinkets_version=4.2.0+26.3
