# https://fabricmc.net/develop
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.3-snapshot-10
minecraft_compat_version=26.3.x

loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=2.5.0+26.3
maven_group=dev.doublekekse
archives_base_name=map_utils

# Dependencies
fabric_api_version=0.158.3+26.3
trinkets_version=4.1.0-rc.1+26.2
#trinkets_version=4.0.0-beta.2+26.1
